/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Nan2026ScapeRouteImport } from './routes/nan2026/scape'
import { Route as Nan2026PhotoRouteImport } from './routes/nan2026/photo'
import { Route as Nan2026NoahofnanRouteImport } from './routes/nan2026/noahofnan'
import { Route as Nan2026NoahRouteImport } from './routes/nan2026/noah'
import { Route as Nan2026MusicRouteImport } from './routes/nan2026/music'
import { Route as Nan2026LifeRouteImport } from './routes/nan2026/life'
import { Route as Nan2026IdeaLabRouteImport } from './routes/nan2026/idea-lab'
import { Route as Nan2026Showcase2026RouteImport } from './routes/nan2026/Showcase2026'
import { Route as FestivalsShowcaseRouteImport } from './routes/festivals/showcase'
import { Route as FestivalsScapeRouteImport } from './routes/festivals/scape'
import { Route as FestivalsPerformativeRouteImport } from './routes/festivals/performative'
import { Route as FestivalsFoodMapRouteImport } from './routes/festivals/food-map'
import { Route as FestivalsCreatorRouteImport } from './routes/festivals/creator'
import { Route as FestivalsCraftRouteImport } from './routes/festivals/craft'
import { Route as CinemaShortFilmRouteImport } from './routes/cinema/short-film'
import { Route as CinemaMusicRouteImport } from './routes/cinema/music'
import { Route as CinemaFilmRouteImport } from './routes/cinema/film'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026ScapeRoute = Nan2026ScapeRouteImport.update({
  id: '/nan2026/scape',
  path: '/nan2026/scape',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026PhotoRoute = Nan2026PhotoRouteImport.update({
  id: '/nan2026/photo',
  path: '/nan2026/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026NoahofnanRoute = Nan2026NoahofnanRouteImport.update({
  id: '/nan2026/noahofnan',
  path: '/nan2026/noahofnan',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026NoahRoute = Nan2026NoahRouteImport.update({
  id: '/nan2026/noah',
  path: '/nan2026/noah',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026MusicRoute = Nan2026MusicRouteImport.update({
  id: '/nan2026/music',
  path: '/nan2026/music',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026LifeRoute = Nan2026LifeRouteImport.update({
  id: '/nan2026/life',
  path: '/nan2026/life',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026IdeaLabRoute = Nan2026IdeaLabRouteImport.update({
  id: '/nan2026/idea-lab',
  path: '/nan2026/idea-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const Nan2026Showcase2026Route = Nan2026Showcase2026RouteImport.update({
  id: '/nan2026/Showcase2026',
  path: '/nan2026/Showcase2026',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsShowcaseRoute = FestivalsShowcaseRouteImport.update({
  id: '/festivals/showcase',
  path: '/festivals/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsScapeRoute = FestivalsScapeRouteImport.update({
  id: '/festivals/scape',
  path: '/festivals/scape',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsPerformativeRoute = FestivalsPerformativeRouteImport.update({
  id: '/festivals/performative',
  path: '/festivals/performative',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsFoodMapRoute = FestivalsFoodMapRouteImport.update({
  id: '/festivals/food-map',
  path: '/festivals/food-map',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsCreatorRoute = FestivalsCreatorRouteImport.update({
  id: '/festivals/creator',
  path: '/festivals/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsCraftRoute = FestivalsCraftRouteImport.update({
  id: '/festivals/craft',
  path: '/festivals/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaShortFilmRoute = CinemaShortFilmRouteImport.update({
  id: '/cinema/short-film',
  path: '/cinema/short-film',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaMusicRoute = CinemaMusicRouteImport.update({
  id: '/cinema/music',
  path: '/cinema/music',
  getParentRoute: () => rootRouteImport,
} as any)
const CinemaFilmRoute = CinemaFilmRouteImport.update({
  id: '/cinema/film',
  path: '/cinema/film',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/timeline': typeof TimelineRoute
  '/cinema/film': typeof CinemaFilmRoute
  '/cinema/music': typeof CinemaMusicRoute
  '/cinema/short-film': typeof CinemaShortFilmRoute
  '/festivals/craft': typeof FestivalsCraftRoute
  '/festivals/creator': typeof FestivalsCreatorRoute
  '/festivals/food-map': typeof FestivalsFoodMapRoute
  '/festivals/performative': typeof FestivalsPerformativeRoute
  '/festivals/scape': typeof FestivalsScapeRoute
  '/festivals/showcase': typeof FestivalsShowcaseRoute
  '/nan2026/Showcase2026': typeof Nan2026Showcase2026Route
  '/nan2026/idea-lab': typeof Nan2026IdeaLabRoute
  '/nan2026/life': typeof Nan2026LifeRoute
  '/nan2026/music': typeof Nan2026MusicRoute
  '/nan2026/noah': typeof Nan2026NoahRoute
  '/nan2026/noahofnan': typeof Nan2026NoahofnanRoute
  '/nan2026/photo': typeof Nan2026PhotoRoute
  '/nan2026/scape': typeof Nan2026ScapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/timeline': typeof TimelineRoute
  '/cinema/film': typeof CinemaFilmRoute
  '/cinema/music': typeof CinemaMusicRoute
  '/cinema/short-film': typeof CinemaShortFilmRoute
  '/festivals/craft': typeof FestivalsCraftRoute
  '/festivals/creator': typeof FestivalsCreatorRoute
  '/festivals/food-map': typeof FestivalsFoodMapRoute
  '/festivals/performative': typeof FestivalsPerformativeRoute
  '/festivals/scape': typeof FestivalsScapeRoute
  '/festivals/showcase': typeof FestivalsShowcaseRoute
  '/nan2026/Showcase2026': typeof Nan2026Showcase2026Route
  '/nan2026/idea-lab': typeof Nan2026IdeaLabRoute
  '/nan2026/life': typeof Nan2026LifeRoute
  '/nan2026/music': typeof Nan2026MusicRoute
  '/nan2026/noah': typeof Nan2026NoahRoute
  '/nan2026/noahofnan': typeof Nan2026NoahofnanRoute
  '/nan2026/photo': typeof Nan2026PhotoRoute
  '/nan2026/scape': typeof Nan2026ScapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/timeline': typeof TimelineRoute
  '/cinema/film': typeof CinemaFilmRoute
  '/cinema/music': typeof CinemaMusicRoute
  '/cinema/short-film': typeof CinemaShortFilmRoute
  '/festivals/craft': typeof FestivalsCraftRoute
  '/festivals/creator': typeof FestivalsCreatorRoute
  '/festivals/food-map': typeof FestivalsFoodMapRoute
  '/festivals/performative': typeof FestivalsPerformativeRoute
  '/festivals/scape': typeof FestivalsScapeRoute
  '/festivals/showcase': typeof FestivalsShowcaseRoute
  '/nan2026/Showcase2026': typeof Nan2026Showcase2026Route
  '/nan2026/idea-lab': typeof Nan2026IdeaLabRoute
  '/nan2026/life': typeof Nan2026LifeRoute
  '/nan2026/music': typeof Nan2026MusicRoute
  '/nan2026/noah': typeof Nan2026NoahRoute
  '/nan2026/noahofnan': typeof Nan2026NoahofnanRoute
  '/nan2026/photo': typeof Nan2026PhotoRoute
  '/nan2026/scape': typeof Nan2026ScapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/timeline'
    | '/cinema/film'
    | '/cinema/music'
    | '/cinema/short-film'
    | '/festivals/craft'
    | '/festivals/creator'
    | '/festivals/food-map'
    | '/festivals/performative'
    | '/festivals/scape'
    | '/festivals/showcase'
    | '/nan2026/Showcase2026'
    | '/nan2026/idea-lab'
    | '/nan2026/life'
    | '/nan2026/music'
    | '/nan2026/noah'
    | '/nan2026/noahofnan'
    | '/nan2026/photo'
    | '/nan2026/scape'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/timeline'
    | '/cinema/film'
    | '/cinema/music'
    | '/cinema/short-film'
    | '/festivals/craft'
    | '/festivals/creator'
    | '/festivals/food-map'
    | '/festivals/performative'
    | '/festivals/scape'
    | '/festivals/showcase'
    | '/nan2026/Showcase2026'
    | '/nan2026/idea-lab'
    | '/nan2026/life'
    | '/nan2026/music'
    | '/nan2026/noah'
    | '/nan2026/noahofnan'
    | '/nan2026/photo'
    | '/nan2026/scape'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/timeline'
    | '/cinema/film'
    | '/cinema/music'
    | '/cinema/short-film'
    | '/festivals/craft'
    | '/festivals/creator'
    | '/festivals/food-map'
    | '/festivals/performative'
    | '/festivals/scape'
    | '/festivals/showcase'
    | '/nan2026/Showcase2026'
    | '/nan2026/idea-lab'
    | '/nan2026/life'
    | '/nan2026/music'
    | '/nan2026/noah'
    | '/nan2026/noahofnan'
    | '/nan2026/photo'
    | '/nan2026/scape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  TimelineRoute: typeof TimelineRoute
  CinemaFilmRoute: typeof CinemaFilmRoute
  CinemaMusicRoute: typeof CinemaMusicRoute
  CinemaShortFilmRoute: typeof CinemaShortFilmRoute
  FestivalsCraftRoute: typeof FestivalsCraftRoute
  FestivalsCreatorRoute: typeof FestivalsCreatorRoute
  FestivalsFoodMapRoute: typeof FestivalsFoodMapRoute
  FestivalsPerformativeRoute: typeof FestivalsPerformativeRoute
  FestivalsScapeRoute: typeof FestivalsScapeRoute
  FestivalsShowcaseRoute: typeof FestivalsShowcaseRoute
  Nan2026Showcase2026Route: typeof Nan2026Showcase2026Route
  Nan2026IdeaLabRoute: typeof Nan2026IdeaLabRoute
  Nan2026LifeRoute: typeof Nan2026LifeRoute
  Nan2026MusicRoute: typeof Nan2026MusicRoute
  Nan2026NoahRoute: typeof Nan2026NoahRoute
  Nan2026NoahofnanRoute: typeof Nan2026NoahofnanRoute
  Nan2026PhotoRoute: typeof Nan2026PhotoRoute
  Nan2026ScapeRoute: typeof Nan2026ScapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/scape': {
      id: '/nan2026/scape'
      path: '/nan2026/scape'
      fullPath: '/nan2026/scape'
      preLoaderRoute: typeof Nan2026ScapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/photo': {
      id: '/nan2026/photo'
      path: '/nan2026/photo'
      fullPath: '/nan2026/photo'
      preLoaderRoute: typeof Nan2026PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/noahofnan': {
      id: '/nan2026/noahofnan'
      path: '/nan2026/noahofnan'
      fullPath: '/nan2026/noahofnan'
      preLoaderRoute: typeof Nan2026NoahofnanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/noah': {
      id: '/nan2026/noah'
      path: '/nan2026/noah'
      fullPath: '/nan2026/noah'
      preLoaderRoute: typeof Nan2026NoahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/music': {
      id: '/nan2026/music'
      path: '/nan2026/music'
      fullPath: '/nan2026/music'
      preLoaderRoute: typeof Nan2026MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/life': {
      id: '/nan2026/life'
      path: '/nan2026/life'
      fullPath: '/nan2026/life'
      preLoaderRoute: typeof Nan2026LifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/idea-lab': {
      id: '/nan2026/idea-lab'
      path: '/nan2026/idea-lab'
      fullPath: '/nan2026/idea-lab'
      preLoaderRoute: typeof Nan2026IdeaLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nan2026/Showcase2026': {
      id: '/nan2026/Showcase2026'
      path: '/nan2026/Showcase2026'
      fullPath: '/nan2026/Showcase2026'
      preLoaderRoute: typeof Nan2026Showcase2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/showcase': {
      id: '/festivals/showcase'
      path: '/festivals/showcase'
      fullPath: '/festivals/showcase'
      preLoaderRoute: typeof FestivalsShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/scape': {
      id: '/festivals/scape'
      path: '/festivals/scape'
      fullPath: '/festivals/scape'
      preLoaderRoute: typeof FestivalsScapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/performative': {
      id: '/festivals/performative'
      path: '/festivals/performative'
      fullPath: '/festivals/performative'
      preLoaderRoute: typeof FestivalsPerformativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/food-map': {
      id: '/festivals/food-map'
      path: '/festivals/food-map'
      fullPath: '/festivals/food-map'
      preLoaderRoute: typeof FestivalsFoodMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/creator': {
      id: '/festivals/creator'
      path: '/festivals/creator'
      fullPath: '/festivals/creator'
      preLoaderRoute: typeof FestivalsCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals/craft': {
      id: '/festivals/craft'
      path: '/festivals/craft'
      fullPath: '/festivals/craft'
      preLoaderRoute: typeof FestivalsCraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/short-film': {
      id: '/cinema/short-film'
      path: '/cinema/short-film'
      fullPath: '/cinema/short-film'
      preLoaderRoute: typeof CinemaShortFilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/music': {
      id: '/cinema/music'
      path: '/cinema/music'
      fullPath: '/cinema/music'
      preLoaderRoute: typeof CinemaMusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinema/film': {
      id: '/cinema/film'
      path: '/cinema/film'
      fullPath: '/cinema/film'
      preLoaderRoute: typeof CinemaFilmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  TimelineRoute: TimelineRoute,
  CinemaFilmRoute: CinemaFilmRoute,
  CinemaMusicRoute: CinemaMusicRoute,
  CinemaShortFilmRoute: CinemaShortFilmRoute,
  FestivalsCraftRoute: FestivalsCraftRoute,
  FestivalsCreatorRoute: FestivalsCreatorRoute,
  FestivalsFoodMapRoute: FestivalsFoodMapRoute,
  FestivalsPerformativeRoute: FestivalsPerformativeRoute,
  FestivalsScapeRoute: FestivalsScapeRoute,
  FestivalsShowcaseRoute: FestivalsShowcaseRoute,
  Nan2026Showcase2026Route: Nan2026Showcase2026Route,
  Nan2026IdeaLabRoute: Nan2026IdeaLabRoute,
  Nan2026LifeRoute: Nan2026LifeRoute,
  Nan2026MusicRoute: Nan2026MusicRoute,
  Nan2026NoahRoute: Nan2026NoahRoute,
  Nan2026NoahofnanRoute: Nan2026NoahofnanRoute,
  Nan2026PhotoRoute: Nan2026PhotoRoute,
  Nan2026ScapeRoute: Nan2026ScapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
